version: '3.8'

services:
    nginx:
        build:
            context: ./docker
            dockerfile: Dockerfile-nginx
        volumes:
            - ./:/var/www/project/:cached
        ports:
            - 8080:80
        networks:
            - symfony
    
    fpm:
        build:
            context: ./docker
            dockerfile: Dockerfile-php
        environment:
            APP_ENV: dev
            DATABASE_URL: mysql://root:root@db/ekookna_sample_form
        volumes:
            - ./:/var/www/project/:cached
        networks:
            - symfony

    db: 
        image: mariadb:10.6.4
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=ekookna_sample_form
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            #- persistent:/var/lib/mysql
            - ./docker/build/db/:/docker-entrypoint-initdb.d/
        networks:
            - symfony

    phpmyadmin:
        image: phpmyadmin:latest
        ports: 
            - "8081:80"
        networks:
            - symfony

networks:
    symfony: